modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
[[mods]]
modId = "gtoepp"
version = "1.0.1"
displayName = "${mod_name}"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[dependencies.gtoepp]]
modId="gtocore"
versionRange="[0.5.0,)"
mandatory=true
ordering="BEFORE"
side="BOTH"
