modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "gtoepp"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[dependencies.gtoepp]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.gtoepp]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.gtoepp]]
modId="gtocore"
versionRange="[0.4.8,)"
mandatory=true
